### ISSUE TITLE
Manifesto

### ISSUE THREAD

**Issue by onur** [aciksozluk/altyapi-tartisma#16]
Bence öncelikle bir manifesto hazırlanmalı ve proje bu doğrultuda ilerlemeli. Manifesto şunları içerebilir:

* Açık Sözlük projesine neden ihtiyaç var
* Açık Sözlük hangi problemleri çözmek için var
* Açık Sözlük projesi geliştirici ve/veya yazarlara nasıl bir güvence veriyor
* Organizasyon yapısı (gelecekte)

vb. gibi konuları belirleyip, işin başında gerek projeyi gerekse ilerde yazı yazmayı planlayan kullanıcıları güvence altına alabiliriz

**Comment by hqv** [comment]
https://eksisozluk.com/entry/58962390

**Comment by onur** [comment]
Evet aynen onun biraz daha sadeleştirilmiş, anlaması kolay ve biraz daha resmi olanından bahsediyorum. Eminim her maddenin birer cümle olduğu bir manifestoyu @sahtepetrucci hazırlayabilir.

**Comment by sahtepetrucci** [comment]
@onur ben sözlükteki entry'nin kişisel kısımlarını çıkarıp, biraz da sadeleştirerek readme dosyasına ekledim. şimdilik genel bir metin olarak elimizin altında bir taslak oldu, bunu şu an tartışılmakta olan lisanslarla ilgili olarak somut bir karara varıldığında zenginleştirebilir - değiştirebilirsiniz.

**Comment by onur** [comment]
Teşekkürler, tam da bahsettiğim şey buydu. Umarım imla kurallarına göre düzenlememde bir sakınca yoktur.

**Comment by sahtepetrucci** [comment]
@onur Estağfurullah, ne sakıncası olacak. :)
