### ISSUE TITLE
Depo adının "aciksozluk" olarak değiştirilmesi

### ISSUE THREAD

**Issue by onur** [aciksozluk/altyapi-tartisma#20]
Bence bu depo altında şimdiden çok önemli konuları tartışıp kararlar almaya başladık. Bu tartışmalar ileride işimize yarayabilir ve/veya referans olarak kullanabiliriz. Bu nedenle projenin tamamiyle bu depo üzerinden yürümesi taraftarıyım.

**Comment by ramesaliyev** [comment]
Depo derken bu repodan mı bahsediyorsun?

**Comment by onur** [comment]
@ramesaliyev evet

**Comment by hqv** [comment]
Bu repositoryaya her zaman gelip sözlüğün yapısı hakkında tartışabiliriz. Ancak sözlüğün asıl kodunun bulunduğu repositoryada sadece kod ile ilgili issue'ların bulunması iyi olur. Her şeyi sınıflandırırız, bug ararken "Neden Mochachinoscript kullanmıyoruz???**?" issue'su görmezsiniz diyorsanız tamam.

**Comment by ramesaliyev** [comment]
@hqv bu repoyu @onur'un dediği gibi bir kalıcı tartışma/karar alma ortamına çevirirsek kodların bulunduğu repoda bu konseptte issue açan arkadaşları buraya yönlendirebiliriz. Böylece fikir/öneri issue'larını ayak altından çekmiş oluruz.

**Comment by onur** [comment]
Ben şahsen herşeyi aynı çatı altında tutma taraftarıyım. Sözlüğün yapısı da sonuçta oluşturulacak ürünün bir parçası. Elbette herşeyin sınıflandırılması gerekli. Mesela ilerleyen günlerde bir iskelet PR'si göndermeyi planlıyorum. Yeni depo aç orda tartışmaya başla sonra geri gel burda sürekli tartışmaya devam et iki de bir depolar arası referans at vs. Şu an açık olan 16 issue'nin sadece 2 tanesi altyapı ile ilgili. Ki altyapı kararları sadece bir kere alınan ve ileride çok fazla değişikliğe uğramayacak şeyler. Eğer bu depoyu kullanmamayı tercih edersek, depoyu büyük ihtimalle kaderine terketmiş oluruz.

Ayrıca bahsettiğiniz insanları farklı depoya yönlendirme fikri de gereksiz bir bürokrasi oluşturmaktan başka bir işe yaramayacağını düşünüyorum. Açık kaynak projelerinde bu tür gereksiz bürokrasilerle insanların şevkini kırmamak da bir o kadar önemli.

**Comment by ramesaliyev** [comment]
Katılmıyorum. İleride onlarca repo olabilir. REST Api, Mobile Site, Desktop Site, Sunucu tarafındaki Renderer, Template'ler, Temalar, Mobile App, Tasarımlar.. Ve şu an akla gelmeyen bir çok şey. Genel geçer konular bu repo üzerinden konuşulabilir ancak her reponun kendini ilgilendiren konuları kendi issue'ları içerisinde konuşulmalı. Bu şekilde focus kayıpları önlenir.

Alakasız repolar arasında alakasız issue'lar açan kişiler de doğru yere yönlendirilmeliler. Şevk kırmamaktan bahsediyorsak o zaman PR merge yapısı da oturtmayalım herkes master'a pushlasın.

**Comment by onur** [comment]
Ben ileride bahsettiğiniz depoları açmayalım demiyorum. *Şu an* için bu deponun geçmişini/issuelerini ayırmaya gerek yok. Bu depoyu terkedip yeni depoya geçersek bundan bir kazanımımız olmamasına rağmen tüm tartışmaları da kaybedip/terkedeceğiz.

**Comment by onur** [comment]
@hqv sonuç? Eğer adını değiştirmeyeceksek yeni bir depo açıp iskeleti #22 orada oluşturalım.

**Comment by hqv** [comment]
[aciksozluk/aciksozluk](https://github.com/aciksozluk/aciksozluk)
