### ISSUE TITLE
kod ve veri işlerinin birbirinden ayrılması

### ISSUE THREAD

**Issue by ramesaliyev** [aciksozluk/altyapi-tartisma#4]
p2p veya distributed de olsa normal bir websitesi de olsa bu repo içerisinde herhangi bir içerik olmamalı diye düşünüyorum. bu reponun amacı manifestoya uygun open source bir sözlük yazılımı geliştirmek olmalı. diğer türlü kendimizi hedef göstermiş oluyoruz. yanlış mıyım?

**Comment by sahtepetrucci** [comment]
Bu repoda database içeriği bulunmaması gerektiği konusuna katılıyorum, ama kendimizi hedef gösterme kısmını anlamadım. :)

**Comment by ramesaliyev** [comment]
Otoriteler tarafından yazılanlardan sorumlu tutulmaktan bahsediyorum, sonra bizden ip filan istemesinler gelip :)

**Comment by sahtepetrucci** [comment]
Ha evet, şimdi düştü jetonum. Elbette burada kod temeli ve dokümantasyon haricinde veri tutmanın bir manası yok.

Ayrıca bu issue başlığı itibarıyla çok vizyoner duruyor, el atmışken din ve devlet işlerini de birbirinden ayırabilseydik keşke. : -)

**Comment by ramesaliyev** [comment]
@sahtepetrucci ah keşke ülkeye issue açıp halledebilsek o konuyu :)
