### ISSUE TITLE
Database Seçimi

### ISSUE THREAD

**Issue by ozziest** [aciksozluk/altyapi-tartisma#8]
Database seçimi konusunu codebase'den ayrı bir başlık altında tartışmayı öneriyorum. Eğer dile göre (uyumluluk açısından) seçim yapılacaksa, codebase başlığından çıkan sonuçtan sonra bu bölüm altında tartışabiliriz.

**Comment by ramesaliyev** [comment]
İlk soru olarak SQL mi NoSQL mi? Bence SQL çünkü sözlük için NoSQL bir db'nin bize sağlayacağı bir fayda yok sanırım? İlişkisel olması daha uygun olacaktır gibi geliyor. Bu nedenle SQL ve hatta PostgreSQL'e veriyorum oyumu. Veritabanları konusunda daha tecrübeli bir arkadaş aydınlatırsa güzel olur.

**Comment by vedatmahir** [comment]
@ramesaliyev Kesinlikle sözlük gibi bir yapıda NoSQL bir fayda sağlamayacaktır. İlişkisel veriler olacağı için SQL kullanmalıyız. Postgres'e bir oy da benden.

Peki Graph Database'i gündemimize almalı mıyız sizce?

**Comment by ozziest** [comment]
API hakkındaki tartışmaları (GraphQL, Rest vs.) ayrı bir başlık altında tartışmayı öneriyorum.

**Comment by hqv** [comment]
PostgreSQL artı bir.

**Comment by ygunayer** [comment]
Graph DB'yi gerektirecek kadar kompleks, fakat NoSQL'de tutulacak kadar da denormalize olmayan bir veri olacak. O nedenle RDBMS diyorum ve oyumu PostgreSQL'den yana kullanıyorum.

**Comment by readtimeout** [comment]
PostgreSQL'e +1 ve bunun yaninda arama islemleri icin elasticsearch kullanilabilir.

**Comment by ozziest** [comment]
@readtimeout konunun çok dağılmaması adına (diğer başlıklarda epey bir dağıttık :) ) affınıza sığınarak arama işlemlerinden hiç bahsetmeyelim diyorum şimdilik. :)

**Comment by erayarslan** [comment]
MongoDB +1

**Comment by FatihErdem** [comment]
MongoDB ya da Postgres'den birisi olabilir. Ama buna karar vermeden once datamiz gercekten relational olmak zorunda mi ya da NoSql olursa ne avantajimiz olur bunu tartismaliyiz.

**Comment by KiPSOFT** [comment]
Ben hala sistemin yenilikçi olması taraftarıyım ve RethinkDB

**Comment by ibalpinar** [comment]
PostgreSQL +1

**Comment by onur** [comment]
PostgreSQL'de hemfikiriz sanırım

**Comment by hqv** [comment]
PostgreSQL seçilmiş gibi? Eğer aramızda bir veritabanı gurusu varsa bilgisini aktarsın lütfen, yoksa kapatıyorum.

**Comment by okanvurdu** [comment]
PostgreSQL +1

**Comment by halid** [comment]
Kapanmış gerçi ama pgsql tarafında destek atarım. Pgsql mantıklı olur.
