### ISSUE TITLE
Server-side rendering yahut client-side rendering

### ISSUE THREAD

**Issue by hqv** [aciksozluk/altyapi-tartisma#9]
Client-side rendering şöyle:
1- Initial request CSS ve javascript'i indirir- içeriğin bir kısmı yahut tamamı yoktur.
2- İndirilen javascript içeriği tamamlamak için requestler yollar.
3- Gelen JSON'ı client parse eder, (neredeyse her zaman) bir templating library vasıtasıyla içeriği oluşturur.

Server-side rendering şöyle:
1- Initial request layout'u, CSS'yi, Javascript'i ve tüm içeriği indirir.
2- Sayfaya yapılan update'ler twitter'daki gibi API requestleri ile client tarafında çizilebilir yahut daha basit şekilde ekşi'deki gibi sayfayı yenilemek suretiyle server'dan bunlar bir daha istenir.

Ben daha basit olması ve client'a çok yük bindirmemesi açısından serverside rendering'i tercih ediyorum. Sitenin güçsüz akıllı telefonları ya da celeronlu laptopları "kastırmasını" ya da NoScript kullanan bir client'ta boş görünmesini istemem.

**Comment by readtimeout** [comment]
Yazilim dunyasi ve teknolojinin ilerleyisi ve yonelimi dusunuldugunde nacizane olarak "Sitenin güçsüz akıllı telefonları ya da celeronlu laptopları "kastırmasını" ya da NoScript kullanan bir client'ta boş görünmesi" gibi bir dusunceyi kafamizdan silmemiz gerektigini dusunuyorum.

Kesinlikle SOA olmali backend ve frontend layerlari birbirinden ayri dusunulmeli. Sahsi fikrimdir tartisabiliriz. Tartisalim ki ideal olani bulabilelim.

**Comment by hqv** [comment]
Yazılım dünyası ve teknolojinin yönelimini sıkı sıkıya takip etme gibi bir zorunluluğumuz ne zamandan beri var? Burada "en yeni teknolojiyle" bir sözlük yapmak için değil, "herkes için erişilebilir ve açık" bir sözlük yapmak için bulunuyoruz.

Şu anda birçok insanda Galaxy Ace benzeri "dandik" telefonların bulunduğundan eminim. Okuma çevresinde dönen bir platform üzerinde çalıştığı aygıtın kaynaklarını zorlarsa çekilmez olur. Eğer saçma sapan rendering engine'lerde ve microcontrollerdan hallice işlemcilerde render edilebilecek bir şey yapılabilecekse o zaman ben de clientside derim.

Amacımız server'a da client'a da en az yükü bindirmek ve bunu yaparken kimseyi içerikten alıkoymamak olmalı.

**Comment by readtimeout** [comment]
Elbetteki "herkes icin erisilebilir ve acik" olmali. Fakat bulundugumuz zamandaki teknolojiyi kullanmadigimizda cok cabuk eskime meydana geliyor. Ayrica katmanli mimari en yeni teknoloji degil. Cogu yazilim/firma katmanlari ayrimak icin ugras verirken (yazilimlar uretirken) boyle guzel bir projede bunun dusunulmesi gerektigine inaniyorum. Evet ugrastirici bir is farkindayim.

**Comment by sahtepetrucci** [comment]
Bu "çok çabuk eskime" meselesi şu açıdan da değerlendirilebilir. Yukarıda bahsi geçen hassasiyetler gözetilmeden, ağırlıklı olarak güncel ve güçlü aygıtları hedefleyen bir yazılım geliştirildiğinde, kaynak kullanımının kısık tutulması gibi bir hedef yerine mümkün olduğunca inovatif bir proje geliştirilmesi arzulandığında, bu sefer insanların cebindeki - dizinin üstündeki aygıtlar açısından "çok çabuk eskime" meydana geliyor.

Bu tabii başka ve daha sosyal bir tartışmanın konusu ama yalnızca verilen teknik kararlarda ister istemez ideolojik bir tercihte de bulunuyoruz, onu vurgulamak istedim.

**Comment by readtimeout** [comment]
Oncelikle guclu kaynaklari hedefleyen yazilimdan bahsetmedigimi belirtmek isterim. Eger kaynak kullanimindan bahsedecek olursak; server-side renderingde olusan html ciktinin her request-response da tekrar tekrar gelmesi ozellikle mobil veri kullaniminda gereksiz trafige neden olacagindan insanlarin bir noktada cebine dokunmus olacaktir. Diger turlu sadece data gelmis olacagi icin trafik kullanimi minimumda tutulmus olacaktir. @sahtepetrucci dediginiz gibi ideolojik bir tercihte de bulunmus oluyoruz.

Ayrica mobil/desktop(twitter mac client gibi) uygulama yapilmaya karar verildiginde direkt olarak uygulamanin kullanacagi servis hazir olacaktir.

Front-end yazilimci olmadigimi belirteyim. Her response sonucu HTML icerigin Browser DOM'a aktarilmasi durumunda kullanilan kaynaklar ile JS ile olusturulan elementlerin (Virtual/Shadow/Browser)DOM'a aktarilmasi sirasinda kullanilan kaynaklar hakkinda bir fikrim yok, ustadlar ona cevap verecektir. Ki katmanli yapilar geregi servis katmani ustune eklenecek bir katman ile server-side rendering de mumkun olabilecektir fakat tersi durumu olustumak cok zor olacaktir.

Konu cok ince detaylara dogru ilerliyor. Elbette ki herseyin artisi oldugu gibi eksisi de var. Ilk commentimde de dedigim uzere onemli olan ideal olani bulmak.

**Comment by ramesaliyev** [comment]
Front-End ve kullanıcının kaynakları konusunda kafa karışıklığı var gibi duruyor. Açıkçası 2016 yılında csr (client-side-rendering) yapmak client-side'a 'çok yük bindirmek' olmuyor. Kaldı ki csr yapmak ilk içerik yüklemesinden sonra performans olarak kullanıcıya da sunucuya da artı sağlayacak bir yönelim. Çünkü ekranda sadece 'ihtiyaç duyulan yerler' değişecek. + sunucu ile yapılan veri alışverişi minimuma inecek. Bu da veri maliyeti olarak sunucuya yansıyacak bir durum.

Benim önerim csr ile ssr (server-side-rendering)'in hybrid bir şekilde çalışacağı bir yapı kurmak. Bunu bir senaryo üzerinden anlatmayı uygun görüyorum;

**Kullanıcı siteye ilk kez girer:**  /entry/123
Site sunucu tarafında render edilip kullanıcıya yollanır. Doğal olarak tüm js-css gibi statik dosyalar da yüklenir ve kullanıcının tarayıcısında cachelenir. Kullanıcının tarayıcısı js destekliyorsa ve desktop ise ya da güçlü bir mobil cihaz ise; front-end app ayağa kaldırılır.

Buradan sonrası client-side app olarak devam eder. site fiziksel olarak yönlenmez. URL vs. değişir yani görünüm olarak sanki sayfalar değişiyormuş gibi olur; ancak her şey tamamen front-end tarafında döner. 

**Kullanıcı bir linki yeni sekmede açar vs** /entry/123
Statik dosyaların tekrar sunucudan yüklenmesi dışında yukarıdaki işlemlerin aynısı tekrarlanır. Sonra yine aynı koşullarla client-side app ayağa kalkar.

Böyle düşününce bana backend tarafında iki yapı olmalı diye geliyor. 

Birincisi **sadece JSON veri sunan bir API** ikincisi ise ilk girişleri karşılayıp siteyi bu birinci json sunan api'den aldığı veri ile render edip sunan bir başka servis.

İşte bu ikinci servis ve client-side app aynı route'ları ve template'leri paylaşacağından (en azından) onun kesinlikle NodeJS olması konusunda ısrarcıyım.    

Siteleri bu şekilde bölmek mobile web siteyi ayırmak istediğimizde veya bir mobile app yapmak istediğimizde işlerimizi epey kolaylaştıracaktır.

**Comment by erayarslan** [comment]
Client-Side Rendering için kodu [şurda](https://github.com/erayarslan/foodbone) olan [şöyle](http://singlepage.ninja/) bi çalışmam var.
İnceleyebilirsiniz. Kararı bu yönde verirseniz de yardımcı olabilirim.
Aksi bir kararda da yardımcı olabilirim.

İyi bir mimari tasarlanması durumunda Single-Page güzel bir çözüm olacaktır bence.

**Comment by hqv** [comment]
@ramesaliyev, olabilir. @sahtepetrucci'nin malum entryde belirttiği progressive enhancement bunu gerektiriyor.

Tabii bunun benchmark'ını, testini yapmak lazım. Basit bir sayfa render edebildiğimizde nasıl scale ettiğine biraz bakarız.

**Comment by thedewil** [comment]
@ramesaliyev;

Referans olması açısından, instela da şu an json içerik yollayan bir rest api üzerinde çalışıyor.

  http://docs.instela.apiary.io/

**Comment by KiPSOFT** [comment]
Bu tartışmada varılan sonucu netleştirelim mi arkadaşlar ?
- REST, Single Page ?
- Server side rendering ?

**Comment by ramesaliyev** [comment]
@KiPSOFT 

Bir itiraz yok ise yukarıda anlattığım yapıyı uygulayalım derim.

**Comment by KiPSOFT** [comment]
@ramesaliyev Ben o yapıya katılıyorum.

**Comment by hqv** [comment]
O zaman issue'yu kapatıyorum. İlk sayfa server-side render, eğer işler yolunda gidiyorsa client-side'a geçiş, yoksa server'dan yollamaya devam.
